export const musicList = [
  { title: "Độ Mixi Hát Trường Sơn Đông Trường Sơn Tây Remix", path: "/Music/y2mate.com - Độ Mixi Hát Trường Sơn Đông Trường Sơn Tây Remix.mp3", artist: "Độ Mixi" },
  { title: "Đan Nguyên Bằng Kiều Quang Lê   Đắp Mộ Cuộc Tình  PBN 126", path: "/Music/y2mate.com - Đan Nguyên Bằng Kiều Quang Lê   Đắp Mộ Cuộc Tình  PBN 126.mp3", artist: "Đan Nguyên, Bằng Kiều, Quang Lê" },
  { title: "mùa xuân ARIRANG karaoke", path: "/Music/y2mate.com - mùa xuân ARIRANG karaoke.mp3", artist: "Unknown" },
  { title: "Way Back Home Về Nhà Thôi  SHAUN ft 20 Nghệ Sĩ Việt Nam  Gala Nhạc Việt Official MV", path: "/Music/y2mate.com - Way Back Home Về Nhà Thôi  SHAUN ft 20 Nghệ Sĩ Việt Nam  Gala Nhạc Việt Official MV.mp3", artist: "SHAUN ft. Various Artists" },
  { title: "Sẽ Không Còn Nữa  Tuấn Hưng", path: "/Music/y2mate.com - Sẽ Không Còn Nữa  Tuấn Hưng.mp3", artist: "Tuấn Hưng" },
  { title: "STREAM ĐẾN BAO GIỜ  ĐỘ MIXI ft BẠN SÁNG TÁC OFFICIAL LYRICS VIDEO", path: "/Music/y2mate.com - STREAM ĐẾN BAO GIỜ  ĐỘ MIXI ft BẠN SÁNG TÁC OFFICIAL LYRICS VIDEO.mp3", artist: "Độ Mixi ft. Bạn Sáng Tác" },
  { title: "RASTZ  ÔNG TRỜI LÀM TỘI ANH CHƯA  MINH HANH x QNT ft TUẤN CRY INSTRUMENTAL", path: "/Music/y2mate.com - RASTZ  ÔNG TRỜI LÀM TỘI ANH CHƯA  MINH HANH x QNT ft TUẤN CRY INSTRUMENTAL.mp3", artist: "MINH HANH x QNT ft TUẤN CRY" },
  { title: "NẮM  HƯƠNG LY  LIVE VERSION", path: "/Music/y2mate.com - NẮM  HƯƠNG LY  LIVE VERSION.mp3", artist: "HƯƠNG LY" },
  { title: "Người Tình Mùa Đông  Như Quỳnh ASIA 6", path: "/Music/y2mate.com - Người Tình Mùa Đông  Như Quỳnh ASIA 6.mp3", artist: "Như Quỳnh" },
  { title: "NEU CONCERT 2022 TÌM LẠI BẦU TRỜI  TUẤN HƯNG", path: "/Music/y2mate.com - NEU CONCERT 2022 TÌM LẠI BẦU TRỜI  TUẤN HƯNG.mp3", artist: "TUẤN HƯNG" },
  { title: "Karaoke Trường Sơn Đông  Trường Sơn Tây Remix", path: "/Music/y2mate.com - Karaoke Trường Sơn Đông  Trường Sơn Tây Remix.mp3", artist: "Unknown" },
  { title: "Hòa Minzy  Độ Mixi song ca Trường Sơn Đông Trường Sơn Tây remix cực cháy", path: "/Music/y2mate.com - Hòa Minzy  Độ Mixi song ca Trường Sơn Đông Trường Sơn Tây remix cực cháy.mp3", artist: "Hòa Minzy, Độ Mixi" },
  { title: "Chiếc Đèn Ông SaoPhúc Wind Remix Official Audio Lyrics Video", path: "/Music/y2mate.com - Chiếc Đèn Ông SaoPhúc Wind Remix Official Audio Lyrics Video.mp3", artist: "Phúc Wind" },
  { title: "VAN SON  Ngày Xuân Vui Cưới  Hoài Linh", path: "/Music/VAN SON  Ngày Xuân Vui Cưới  Hoài Linh.mp3", artist: "Hoài Linh" },
  { title: "UEFA Champions League Anthem Full Version", path: "/Music/UEFA Champions League Anthem Full Version.mp3", artist: "UEFA" },
  { title: "Tru Mua - Umie (RiverDLove Remix) (RE-UP)", path: "/Music/Tru Mua - Umie (RiverDLove Remix) (RE-UP).mp3", artist: "Umie" },
  { title: "Super Sentai 45th Anniversary Hero Getter", path: "/Music/Super Sentai 45th Anniversary Hero Getter.mp3", artist: "Super Sentai" },
  { title: "Ngày Xưa Ơi  Bảo Trâm  Mây Saigon", path: "/Music/Ngày Xưa Ơi  Bảo Trâm  Mây Saigon.mp3", artist: "Bảo Trâm, Mây Saigon" },
  { title: "Mùa Yêu  The Wall Nutszz Official Music Video", path: "/Music/Mùa Yêu  The Wall Nutszz Official Music Video.mp3", artist: "The Wall Nutszz" },
  { title: "Mocha Lyrics Video  The Wall Nutszz", path: "/Music/Mocha Lyrics Video  The Wall Nutszz.mp3", artist: "The Wall Nutszz" },
  { title: "Mashup Tôi Người Việt Nam x Quê Hương Việt Nam  Nhóm Xuân Hạ Thu Đông hòa giọng cảm xúc", path: "/Music/Mashup Tôi Người Việt Nam x Quê Hương Việt Nam  Nhóm Xuân Hạ Thu Đông hòa giọng cảm xúc.mp3", artist: "Nhóm Xuân Hạ Thu Đông" },
  { title: "KHÁT VỌNG TUỔI TRẺ  ---  Phương Mỹ Chi & Hoàng Dũng  Chung kết Đường lên đỉnh Olympia năm thứ 24", path: "/Music/KHÁT VỌNG TUỔI TRẺ  ---  Phương Mỹ Chi & Hoàng Dũng  Chung kết Đường lên đỉnh Olympia năm thứ 24.mp3", artist: "Phương Mỹ Chi & Hoàng Dũng" },
  { title: "Gánh Mẹ", path: "/Music/Gánh Mẹ.mp3", artist: "Unknown" },
  { title: "Gokaiger opening", path: "/Music/Gokaiger opening.mp3", artist: "Gokaiger" },
  { title: "FAI Songs _0_1731678983417", path: "/Music/FAI Songs _0_1731678983417.mp3", artist: "Unknown" },
]; 